spring.application.name=job-tracker

# --- Database Connection ---
# Tell Spring Boot where your PostgreSQL database is
spring.datasource.url=jdbc:postgresql://localhost:5432/jobtracker
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# update = create or update tables automatically based on your Java classes
# This means you never have to write CREATE TABLE SQL by hand
spring.jpa.hibernate.ddl-auto=update

# Show the SQL Hibernate generates in the console ? very useful for learning
spring.jpa.show-sql=true

# Format that SQL so it's readable
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false